#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            // Backpacks
            "TACU_Vanguard_B_AP_Kitbag_Green",
            "TACU_Vanguard_B_AP_Kitbag_Tan",
            "TACU_Vanguard_B_AP_Kitbag_White",
            "TACU_Vanguard_B_AT_Kitbag_Green",
            "TACU_Vanguard_B_AT_Kitbag_Tan",
            "TACU_Vanguard_B_AT_Kitbag_White",
            "TACU_Vanguard_B_Medic_AssaultPack_Black",
            "TACU_Vanguard_B_Medic_Kitbag_Green",
            "TACU_Vanguard_B_Medic_Kitbag_Tan",
            "TACU_Vanguard_B_Medic_Kitbag_White",
            "TACU_Vanguard_B_MG_Kitbag_Green",
            "TACU_Vanguard_B_MG_Kitbag_Tan",
            "TACU_Vanguard_B_MG_Kitbag_Winter",
            // Independent - Units
            "TACU_Vanguard_U_I_Contractor_Green_Rifleman_01",
            "TACU_Vanguard_U_I_Contractor_Green_Rifleman_02",
            "TACU_Vanguard_U_I_Contractor_Green_Rifleman_AT",
            "TACU_Vanguard_U_I_Contractor_Green_Rifleman_AP",
            "TACU_Vanguard_U_I_Contractor_Green_Grenadier",
            "TACU_Vanguard_U_I_Contractor_Green_Marksman",
            "TACU_Vanguard_U_I_Contractor_Green_Driver",
            "TACU_Vanguard_U_I_Contractor_Green_TeamLeader",
            "TACU_Vanguard_U_I_Contractor_Green_Autorifleman",
            "TACU_Vanguard_U_I_Contractor_Green_Medic",
            "TACU_Vanguard_U_I_Contractor_Green_Engineer",
            "TACU_Vanguard_U_I_Contractor_Pilot",
            "TACU_Vanguard_U_I_Contractor_Sand_Rifleman_01",
            "TACU_Vanguard_U_I_Contractor_Sand_Rifleman_02",
            "TACU_Vanguard_U_I_Contractor_Sand_Rifleman_AT",
            "TACU_Vanguard_U_I_Contractor_Sand_Rifleman_AP",
            "TACU_Vanguard_U_I_Contractor_Sand_Grenadier",
            "TACU_Vanguard_U_I_Contractor_Sand_Marksman",
            "TACU_Vanguard_U_I_Contractor_Sand_Driver",
            "TACU_Vanguard_U_I_Contractor_Sand_TeamLeader",
            "TACU_Vanguard_U_I_Contractor_Sand_Autorifleman",
            "TACU_Vanguard_U_I_Contractor_Sand_Medic",
            "TACU_Vanguard_U_I_Contractor_Sand_Engineer",
            "TACU_Vanguard_U_I_Contractor_Winter_Rifleman_01",
            "TACU_Vanguard_U_I_Contractor_Winter_Rifleman_02",
            "TACU_Vanguard_U_I_Contractor_Winter_Rifleman_AT",
            "TACU_Vanguard_U_I_Contractor_Winter_Rifleman_AP",
            "TACU_Vanguard_U_I_Contractor_Winter_Grenadier",
            "TACU_Vanguard_U_I_Contractor_Winter_Marksman",
            "TACU_Vanguard_U_I_Contractor_Winter_TeamLeader",
            "TACU_Vanguard_U_I_Contractor_Winter_Autorifleman",
            "TACU_Vanguard_U_I_Contractor_Winter_Medic",
            "TACU_Vanguard_U_I_Specialist_Rifleman",
            "TACU_Vanguard_U_I_Specialist_Rifleman_AT",
            "TACU_Vanguard_U_I_Specialist_Grenadier",
            "TACU_Vanguard_U_I_Specialist_Marksman",
            "TACU_Vanguard_U_I_Specialist_Driver",
            "TACU_Vanguard_U_I_Specialist_TeamLeader",
            "TACU_Vanguard_U_I_Specialist_Autorifleman",
            "TACU_Vanguard_U_I_Specialist_Medic",
            // Independent - Vehicles
            "TACU_Vanguard_V_I_UH80_Ghosthawk",
            "TACU_Vanguard_V_I_AH9_Pawnee",
            "TACU_Vanguard_V_I_Offroad_Armed",
            "TACU_Vanguard_V_I_Dagor_Green",
            "TACU_Vanguard_V_I_Dagor_Armed_Green",
            "TACU_Vanguard_V_I_AFV4_Gorgon",
            "TACU_Vanguard_V_I_Hunter",
            "TACU_Vanguard_V_I_Dagor_Tan",
            "TACU_Vanguard_V_I_Dagor_Armed_Tan",
            "TACU_Vanguard_V_I_Strider",
            "TACU_Vanguard_V_I_Qilin",
            "TACU_Vanguard_V_I_Armed_Qilin",
            // Independent - Turrets
            "TACU_Vanguard_V_I_MK6_Green",
            "TACU_Vanguard_V_I_MK6_Sand",
            "TACU_Vanguard_V_I_MK6_Winter",
            "TACU_Vanguard_V_I_HMG_Green",
            "TACU_Vanguard_V_I_HMG_Sand",
            "TACU_Vanguard_V_I_HMG_Winter",
            "TACU_Vanguard_V_I_Mini_Spike_AT_Green",
            "TACU_Vanguard_V_I_Mini_Spike_AT_Sand",
            "TACU_Vanguard_V_I_ZU23_Green",
            "TACU_Vanguard_V_I_ZU23_Sand",
            // Opfor - Units
            "TACU_Vanguard_U_O_Contractor_Green_Rifleman_01",
            "TACU_Vanguard_U_O_Contractor_Green_Rifleman_02",
            "TACU_Vanguard_U_O_Contractor_Green_Rifleman_AT",
            "TACU_Vanguard_U_O_Contractor_Green_Rifleman_AP",
            "TACU_Vanguard_U_O_Contractor_Green_Grenadier",
            "TACU_Vanguard_U_O_Contractor_Green_Marksman",
            "TACU_Vanguard_U_O_Contractor_Green_Driver",
            "TACU_Vanguard_U_O_Contractor_Green_TeamLeader",
            "TACU_Vanguard_U_O_Contractor_Green_Autorifleman",
            "TACU_Vanguard_U_O_Contractor_Green_Medic",
            "TACU_Vanguard_U_O_Contractor_Green_Engineer",
            "TACU_Vanguard_U_O_Contractor_Pilot",
            "TACU_Vanguard_U_O_Contractor_Sand_Rifleman_01",
            "TACU_Vanguard_U_O_Contractor_Sand_Rifleman_02",
            "TACU_Vanguard_U_O_Contractor_Sand_Rifleman_AT",
            "TACU_Vanguard_U_O_Contractor_Sand_Rifleman_AP",
            "TACU_Vanguard_U_O_Contractor_Sand_Grenadier",
            "TACU_Vanguard_U_O_Contractor_Sand_Marksman",
            "TACU_Vanguard_U_O_Contractor_Sand_Driver",
            "TACU_Vanguard_U_O_Contractor_Sand_TeamLeader",
            "TACU_Vanguard_U_O_Contractor_Sand_Autorifleman",
            "TACU_Vanguard_U_O_Contractor_Sand_Medic",
            "TACU_Vanguard_U_O_Contractor_Sand_Engineer",
            "TACU_Vanguard_U_O_Contractor_Winter_Rifleman_01",
            "TACU_Vanguard_U_O_Contractor_Winter_Rifleman_02",
            "TACU_Vanguard_U_O_Contractor_Winter_Rifleman_AT",
            "TACU_Vanguard_U_O_Contractor_Winter_Rifleman_AP",
            "TACU_Vanguard_U_O_Contractor_Winter_Grenadier",
            "TACU_Vanguard_U_O_Contractor_Winter_Marksman",
            "TACU_Vanguard_U_O_Contractor_Winter_TeamLeader",
            "TACU_Vanguard_U_O_Contractor_Winter_Autorifleman",
            "TACU_Vanguard_U_O_Contractor_Winter_Medic",
            "TACU_Vanguard_U_O_Specialist_Rifleman",
            "TACU_Vanguard_U_O_Specialist_Rifleman_AT",
            "TACU_Vanguard_U_O_Specialist_Grenadier",
            "TACU_Vanguard_U_O_Specialist_Marksman",
            "TACU_Vanguard_U_O_Specialist_Driver",
            "TACU_Vanguard_U_O_Specialist_TeamLeader",
            "TACU_Vanguard_U_O_Specialist_Autorifleman",
            "TACU_Vanguard_U_O_Specialist_Medic",
            // Opfor - Vehicles
            "TACU_Vanguard_V_O_UH80_Ghosthawk",
            "TACU_Vanguard_V_O_AH9_Pawnee",
            "TACU_Vanguard_V_O_Offroad_Armed",
            "TACU_Vanguard_V_O_Dagor_Green",
            "TACU_Vanguard_V_O_Dagor_Armed_Green",
            "TACU_Vanguard_V_O_AFV4_Gorgon",
            "TACU_Vanguard_V_O_Hunter",
            "TACU_Vanguard_V_O_Dagor_Tan",
            "TACU_Vanguard_V_O_Dagor_Armed_Tan",
            "TACU_Vanguard_V_O_Strider",
            "TACU_Vanguard_V_O_Qilin",
            "TACU_Vanguard_V_O_Armed_Qilin",
            // Opfor - Turrets
            "TACU_Vanguard_V_O_MK6_Green",
            "TACU_Vanguard_V_O_MK6_Sand",
            "TACU_Vanguard_V_O_MK6_Winter",
            "TACU_Vanguard_V_O_HMG_Green",
            "TACU_Vanguard_V_O_HMG_Sand",
            "TACU_Vanguard_V_O_HMG_Winter",
            "TACU_Vanguard_V_O_Mini_Spike_AT_Green",
            "TACU_Vanguard_V_O_Mini_Spike_AT_Sand",
            "TACU_Vanguard_V_O_ZU23_Green",
            "TACU_Vanguard_V_O_ZU23_Sand"
        };
        weapons[] = {
            "TACU_Vanguard_W_Sand_F2000",
            "TACU_Vanguard_W_Sand_AK12",
            "TACU_Vanguard_W_Sand_QBZ",
            "TACU_Vanguard_W_Sand_HK416A5GL",
            "TACU_Vanguard_W_Sand_SIG556",
            "TACU_Vanguard_W_Sand_MK200",
            "TACU_Vanguard_W_Sand_FNX",
            "TACU_Vanguard_W_Green_F2000",
            "TACU_Vanguard_W_Green_AK12",
            "TACU_Vanguard_W_Green_QBZ",
            "TACU_Vanguard_W_Green_HK416A5GL",
            "TACU_Vanguard_W_Green_SIG556",
            "TACU_Vanguard_W_Green_MX",
            "TACU_Vanguard_W_Green_MK200",
            "TACU_Vanguard_W_Green_FNX",
            "TACU_Vanguard_W_Winter_HK416A5",
            "TACU_Vanguard_W_Winter_AK12",
            "TACU_Vanguard_W_Winter_QBZ",
            "TACU_Vanguard_W_Winter_HK416A5GL",
            "TACU_Vanguard_W_Winter_SIG556",
            "TACU_Vanguard_W_Winter_MX",
            "TACU_Vanguard_W_Specialists_MXM",
            "TACU_Vanguard_W_Specialists_ARX",
            "TACU_Vanguard_W_Specialists_MX",
            "TACU_Vanguard_W_Specialists_MXGL",
            "TACU_Vanguard_W_Specialists_MXSW",
            "TACU_Vanguard_W_Specialists_MXC",
            "TACU_Vanguard_W_Specialists_Rook"
        };
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {"tacu_main", "tacu_assets"};
        author = ECSTRING(main,Author);
        authors[] = {"Mike"};
        VERSION_CONFIG;
    };
};

#include "CfgFactionClasses.hpp"
#include "CfgGroups.hpp"
#include "CfgVehicles.hpp"
#include "CfgWeapons.hpp"
