class CUP_B_HMMWV_M2_GPK_ACR: CUP_HMMWV_M2_GPK_Base {
    class EventHandlers;
};

class TACU_HMMWV_M2_Base: CUP_B_HMMWV_M2_GPK_ACR {
    MACRO_CLEAR_VEHICLE_CARGO;
    MACRO_DEFAULT_CUP_VEHICLE;

    MACRO_EVENTHANDLERS;
};
