class CUP_B_M113A3_desert_USA: CUP_M113A3_Base {
    class EventHandlers;
};

class TACU_M113A3_Base: CUP_B_M113A3_desert_USA {
    MACRO_CLEAR_VEHICLE_CARGO;
    MACRO_DEFAULT_CUP_VEHICLE;

    MACRO_EVENTHANDLERS;
};
