// Helmet, Item & Vest Base
class Headgear_Base_F;
class Item_Base_F;
class Vest_Base_F;

// Backpacks
class B_FieldPack_Base;

// Uniform Base
class I_G_Soldier_LAT_F;
class I_soldier_F;
class I_Soldier_02_F;
class I_C_Soldier_Bandit_2_F;
class C_Uniform_ArtTShirt_01_v1_F;
class I_E_Uniform_01_coveralls_F;
class I_E_Uniform_01_F;
class I_E_Uniform_01_officer_F;
class I_E_Uniform_01_shortsleeve_F;
class I_L_Uniform_01_camo_F;
class O_A_Soldier_lxWS;

// Vehicles
class APC_Wheeled_02_base_v2_F;
class APC_Wheeled_02_hmg_base_lxws;
class APC_Wheeled_02_unarmed_base_lxws;
class AFV_Wheeled_01_base_F;
class AFV_Wheeled_01_up_base_F;
class B_APC_Tracked_01_base_F;
class B_APC_Wheeled_01_base_F;
class Boat_Armed_01_base_F;
class Heli_Attack_01_dynamicLoadout_base_F;
class Heli_Light_01_dynamicLoadout_base_F;
class Heli_Light_02_dynamicLoadout_base_F;
class Heli_Light_02_unarmed_base_F;
class Heli_light_03_dynamicLoadout_base_F;
class Heli_light_03_unarmed_base_F;
class Heli_Transport_01_base_F;
class Heli_Transport_02_base_F;
class Heli_Transport_03_base_F;
class Heli_Transport_03_unarmed_base_F;
class I_APC_tracked_03_base_F;
class I_APC_Wheeled_03_base_F;
class I_G_Offroad_01_armed_F;
class I_G_Offroad_01_armor_armed_lxWS;
class I_G_Offroad_01_armor_AT_lxWS;
class I_G_Offroad_01_armor_base_lxWS;
class I_G_Offroad_01_AT_F;
class I_G_Offroad_01_F;
class I_G_Van_01_transport_F;
class I_MBT_03_base_F;
class LSV_01_armed_base_F;
class LSV_01_AT_base_F;
class LSV_01_unarmed_base_F;
class LSV_02_armed_base_F;
class LSV_02_AT_base_F;
class LSV_02_unarmed_base_F;
class LT_01_AT_base_F;
class LT_01_cannon_base_F;
class MRAP_01_base_F;
class MRAP_01_gmg_base_F;
class MRAP_01_hmg_base_F;
class MRAP_02_base_F;
class MRAP_02_gmg_base_F;
class MRAP_02_hmg_base_F;
class MRAP_03_base_F;
class MRAP_03_gmg_base_F;
class MRAP_03_hmg_base_F;
class O_APC_Tracked_02_base_F;
class Offroad_01_military_covered_base_F;
class Offroad_02_AT_base_F;
class Offroad_02_LMG_base_F;
class Offroad_02_unarmed_base_F;
class Rubber_duck_base_F;
class Truck_01_base_F;
class Truck_02_aa_base_lxWS;
class Truck_02_base_F;
class Truck_02_MRL_base_F;
class Truck_02_transport_base_F;
class Truck_03_base_F;
class Van_02_transport_base_F;
class Van_02_vehicle_base_F;

// Weapons
class Weapon_Base_F;

// Turrets - Vanilla
class B_G_HMG_02_high_F;
class B_G_Mortar_01_F;
class AT_01_base_F;
class I_HMG_02_F;
class zu23_base_lxWS;
