class Uniform_Base;
class UniformItem;
class H_HelmetSpecB;
class H_PASGT_neckprot_blue_press_F;
class V_PlateCarrier1_blk;
class V_PlateCarrierIAGL_oli;
class V_PlateCarrierL_CTRG;
class V_PlateCarrierH_CTRG;
class V_PlateCarrier1_rgr_noflag_F;
