#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            // Ground Items
            "TACU_MSF_Item_Uniform_CBRN_Black",
            "TACU_MSF_Item_Uniform_Combat_TigerBlack",
            "TACU_MSF_Item_Uniform_Combat_TigerDesert",
            "TACU_MSF_Item_Uniform_Combat_TigerWood",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_LS_Black",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_RS_Black",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_LS_Citrullus",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_RS_Citrullus",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_LS_DDPM",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_RS_DDPM",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_LS_Desert_Fox",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_RS_Desert_Fox",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_LS_Desert_Tiger",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_RS_Desert_Tiger",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_LS_DPM",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_RS_DPM",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_LS_German_Flecktarn",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_RS_German_Flecktarn",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_LS_Horsky",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_RS_Horsky",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_LS_Jungle_Tiger",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_RS_Jungle_Tiger",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_LS_Khaki",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_RS_Khaki",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_LS_Letni",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_RS_Letni",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_LS_Multicam",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_RS_Multicam",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_LS_Olive",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_RS_Olive",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_LS_Rhodesian_Bushstroke",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_RS_Rhodesian_Bushstroke",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_LS_Type3_Flecktarn",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_RS_Type3_Flecktarn",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_LS_Urban_Tiger",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_RS_Urban_Tiger",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_LS_Wetworks",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_RS_Wetworks",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_LS_Woodland",
            "TACU_MSF_Item_Uniform_Combat_Fatigues_RS_Woodland",
            "TACU_MSF_Item_Uniform_Prisoner_Outfit_Orange_Clean",
            "TACU_MSF_Item_Uniform_Prisoner_Outfit_Orange_Dirty",
            "TACU_MSF_Item_Uniform_Prisoner_Outfit_Orange_Muddy",
            "TACU_MSF_Item_Uniform_Prisoner_Outfit_Blue_Clean",
            "TACU_MSF_Item_Uniform_Prisoner_Outfit_Blue_Dirty",
            "TACU_MSF_Item_Uniform_Prisoner_Outfit_Blue_Muddy",
            "TACU_MSF_Item_Uniform_Prisoner_Outfit_Olive_Clean",
            "TACU_MSF_Item_Uniform_Prisoner_Outfit_Olive_Dirty",
            "TACU_MSF_Item_Uniform_Prisoner_Outfit_Olive_Muddy",
            "TACU_MSF_Item_Vest_HeavyPlateCarrier_Black",
            "TACU_MSF_Item_Vest_HeavyPlateCarrier_Coyote",
            "TACU_MSF_Item_Vest_HeavyPlateCarrier_Green",
            "TACU_MSF_Item_Vest_PlateCarrier_Black",
            "TACU_MSF_Item_Vest_PlateCarrier_Coyote",
            "TACU_MSF_Item_Vest_PlateCarrier_Green",
            "TACU_MSF_Item_Vest_ChestRig_Green",
            "TACU_MSF_Item_Vest_ChestRig_Black",
            "TACU_MSF_Item_Vest_ChestRig_Khaki",
            // Backpacks
            "TACU_MSF_B_Poncho_Dry",
            "TACU_MSF_B_Poncho_Wet",
            "TACU_MSF_B_AT_Black",
            "TACU_MSF_B_AT_Coyote",
            "TACU_MSF_B_AT_Green",
            "TACU_MSF_B_Engineer_Black",
            "TACU_MSF_B_Engineer_Coyote",
            "TACU_MSF_B_Engineer_Green",
            "TACU_MSF_B_HAT_Black",
            "TACU_MSF_B_HAT_Coyote",
            "TACU_MSF_B_HAT_Green",
            "TACU_MSF_B_Medic_Black",
            "TACU_MSF_B_Medic_Coyote",
            "TACU_MSF_B_Medic_Green",
            "TACU_MSF_B_MMG_Black",
            "TACU_MSF_B_MMG_Coyote",
            "TACU_MSF_B_MMG_Green",
            // Units (Indep - Combat Black)
            "TACU_MSF_U_I_Regular_Black_Autorifleman",
            "TACU_MSF_U_I_Regular_Black_Crewman",
            "TACU_MSF_U_I_Regular_Black_Engineer",
            "TACU_MSF_U_I_Regular_Black_Grenadier",
            "TACU_MSF_U_I_Regular_Black_HAT",
            "TACU_MSF_U_I_Regular_Black_Marksman",
            "TACU_MSF_U_I_Regular_Black_Medic",
            "TACU_MSF_U_I_Regular_Black_MMG",
            "TACU_MSF_U_I_Regular_Black_Pilot",
            "TACU_MSF_U_I_Regular_Black_Rifleman_01",
            "TACU_MSF_U_I_Regular_Black_Rifleman_AT",
            "TACU_MSF_U_I_Regular_Black_SMG",
            "TACU_MSF_U_I_Regular_Black_Sniper",
            "TACU_MSF_U_I_Regular_Black_TeamLeader",
            // Units (Indep - Combat Desert)
            "TACU_MSF_U_I_Regular_Desert_Autorifleman",
            "TACU_MSF_U_I_Regular_Desert_Engineer",
            "TACU_MSF_U_I_Regular_Desert_Grenadier",
            "TACU_MSF_U_I_Regular_Desert_HAT",
            "TACU_MSF_U_I_Regular_Desert_Marksman",
            "TACU_MSF_U_I_Regular_Desert_Medic",
            "TACU_MSF_U_I_Regular_Desert_MMG",
            "TACU_MSF_U_I_Regular_Desert_Rifleman_01",
            "TACU_MSF_U_I_Regular_Desert_Rifleman_AT",
            "TACU_MSF_U_I_Regular_Desert_SMG",
            "TACU_MSF_U_I_Regular_Desert_Sniper",
            "TACU_MSF_U_I_Regular_Desert_TeamLeader",
            // Units (Indep - Combat Wood)
            "TACU_MSF_U_I_Regular_Wood_Autorifleman",
            "TACU_MSF_U_I_Regular_Wood_Engineer",
            "TACU_MSF_U_I_Regular_Wood_Grenadier",
            "TACU_MSF_U_I_Regular_Wood_HAT",
            "TACU_MSF_U_I_Regular_Wood_Marksman",
            "TACU_MSF_U_I_Regular_Wood_Medic",
            "TACU_MSF_U_I_Regular_Wood_MMG",
            "TACU_MSF_U_I_Regular_Wood_Rifleman_01",
            "TACU_MSF_U_I_Regular_Wood_Rifleman_AT",
            "TACU_MSF_U_I_Regular_Wood_SMG",
            "TACU_MSF_U_I_Regular_Wood_Sniper",
            "TACU_MSF_U_I_Regular_Wood_TeamLeader",
            // Units (Indep - Diamond Dogs Black)
            "TACU_MSF_U_I_DDogs_Black_Autorifleman",
            "TACU_MSF_U_I_DDogs_Black_Engineer",
            "TACU_MSF_U_I_DDogs_Black_Grenadier",
            "TACU_MSF_U_I_DDogs_Black_Marksman",
            "TACU_MSF_U_I_DDogs_Black_Medic",
            "TACU_MSF_U_I_DDogs_Black_Rifleman_01",
            "TACU_MSF_U_I_DDogs_Black_Rifleman_AT",
            "TACU_MSF_U_I_DDogs_Black_Teamleader",
            // Units (Indep - Diamond Dogs Desert)
            "TACU_MSF_U_I_DDogs_Desert_Autorifleman",
            "TACU_MSF_U_I_DDogs_Desert_Engineer",
            "TACU_MSF_U_I_DDogs_Desert_Grenadier",
            "TACU_MSF_U_I_DDogs_Desert_Marksman",
            "TACU_MSF_U_I_DDogs_Desert_Medic",
            "TACU_MSF_U_I_DDogs_Desert_Rifleman_01",
            "TACU_MSF_U_I_DDogs_Desert_Rifleman_AT",
            "TACU_MSF_U_I_DDogs_Desert_Teamleader",
            // Units (Indep - Diamond Dogs Wood)
            "TACU_MSF_U_I_DDogs_Wood_Autorifleman",
            "TACU_MSF_U_I_DDogs_Wood_Engineer",
            "TACU_MSF_U_I_DDogs_Wood_Grenadier",
            "TACU_MSF_U_I_DDogs_Wood_Marksman",
            "TACU_MSF_U_I_DDogs_Wood_Medic",
            "TACU_MSF_U_I_DDogs_Wood_Rifleman_01",
            "TACU_MSF_U_I_DDogs_Wood_Rifleman_AT",
            "TACU_MSF_U_I_DDogs_Wood_Teamleader",
            // Units (Indep - Foxhound Special Forces)
            "TACU_MSF_U_I_Foxhound_Rifleman_01",
            "TACU_MSF_U_I_Foxhound_Marksman",
            "TACU_MSF_U_I_Foxhound_SMG_01",
            // Units (Indep - XOF CBRN Unit)
            "TACU_MSF_U_I_XOF_Rifleman_01",
            "TACU_MSF_U_I_XOF_Grenadier",
            "TACU_MSF_U_I_XOF_SMG_01",
            "TACU_MSF_U_I_XOF_SMG_02",
            "TACU_MSF_U_I_XOF_SMG_03",
            "TACU_MSF_U_I_XOF_Breacher",
            // Units (Opfor - Combat Black)
            "TACU_MSF_U_O_Regular_Black_Autorifleman",
            "TACU_MSF_U_O_Regular_Black_Crewman",
            "TACU_MSF_U_O_Regular_Black_Engineer",
            "TACU_MSF_U_O_Regular_Black_Grenadier",
            "TACU_MSF_U_O_Regular_Black_HAT",
            "TACU_MSF_U_O_Regular_Black_Marksman",
            "TACU_MSF_U_O_Regular_Black_Medic",
            "TACU_MSF_U_O_Regular_Black_MMG",
            "TACU_MSF_U_O_Regular_Black_Pilot",
            "TACU_MSF_U_O_Regular_Black_Rifleman_01",
            "TACU_MSF_U_O_Regular_Black_Rifleman_AT",
            "TACU_MSF_U_O_Regular_Black_SMG",
            "TACU_MSF_U_O_Regular_Black_Sniper",
            "TACU_MSF_U_O_Regular_Black_TeamLeader",
            // Units (Opfor - Combat Desert)
            "TACU_MSF_U_O_Regular_Desert_Autorifleman",
            "TACU_MSF_U_O_Regular_Desert_Engineer",
            "TACU_MSF_U_O_Regular_Desert_Grenadier",
            "TACU_MSF_U_O_Regular_Desert_HAT",
            "TACU_MSF_U_O_Regular_Desert_Marksman",
            "TACU_MSF_U_O_Regular_Desert_Medic",
            "TACU_MSF_U_O_Regular_Desert_MMG",
            "TACU_MSF_U_O_Regular_Desert_Rifleman_01",
            "TACU_MSF_U_O_Regular_Desert_Rifleman_AT",
            "TACU_MSF_U_O_Regular_Desert_SMG",
            "TACU_MSF_U_O_Regular_Desert_Sniper",
            "TACU_MSF_U_O_Regular_Desert_TeamLeader",
            // Units (Opfor - Combat Wood)
            "TACU_MSF_U_O_Regular_Wood_Autorifleman",
            "TACU_MSF_U_O_Regular_Wood_Engineer",
            "TACU_MSF_U_O_Regular_Wood_Grenadier",
            "TACU_MSF_U_O_Regular_Wood_HAT",
            "TACU_MSF_U_O_Regular_Wood_Marksman",
            "TACU_MSF_U_O_Regular_Wood_Medic",
            "TACU_MSF_U_O_Regular_Wood_MMG",
            "TACU_MSF_U_O_Regular_Wood_Rifleman_01",
            "TACU_MSF_U_O_Regular_Wood_Rifleman_AT",
            "TACU_MSF_U_O_Regular_Wood_SMG",
            "TACU_MSF_U_O_Regular_Wood_Sniper",
            "TACU_MSF_U_O_Regular_Wood_TeamLeader",
            // Units (Opfor - Diamond Dogs Black)
            "TACU_MSF_U_O_DDogs_Black_Autorifleman",
            "TACU_MSF_U_O_DDogs_Black_Engineer",
            "TACU_MSF_U_O_DDogs_Black_Grenadier",
            "TACU_MSF_U_O_DDogs_Black_Marksman",
            "TACU_MSF_U_O_DDogs_Black_Medic",
            "TACU_MSF_U_O_DDogs_Black_Rifleman_01",
            "TACU_MSF_U_O_DDogs_Black_Rifleman_AT",
            "TACU_MSF_U_O_DDogs_Black_Teamleader",
            // Units (Opfor - Diamond Dogs Desert)
            "TACU_MSF_U_O_DDogs_Desert_Autorifleman",
            "TACU_MSF_U_O_DDogs_Desert_Engineer",
            "TACU_MSF_U_O_DDogs_Desert_Grenadier",
            "TACU_MSF_U_O_DDogs_Desert_Rifleman_01",
            "TACU_MSF_U_O_DDogs_Desert_Rifleman_AT",
            "TACU_MSF_U_O_DDogs_Desert_Marksman",
            "TACU_MSF_U_O_DDogs_Desert_Medic",
            "TACU_MSF_U_O_DDogs_Desert_Teamleader",
            // Units (Opfor - Diamond Dogs Wood)
            "TACU_MSF_U_O_DDogs_Wood_Autorifleman",
            "TACU_MSF_U_O_DDogs_Wood_Engineer",
            "TACU_MSF_U_O_DDogs_Wood_Grenadier",
            "TACU_MSF_U_O_DDogs_Wood_Marksman",
            "TACU_MSF_U_O_DDogs_Wood_Medic",
            "TACU_MSF_U_O_DDogs_Wood_Rifleman_01",
            "TACU_MSF_U_O_DDogs_Wood_Rifleman_AT",
            "TACU_MSF_U_O_DDogs_Wood_Teamleader",
            // Units (Opfor - Foxhound Special Forces)
            "TACU_MSF_U_O_Foxhound_Rifleman_01",
            "TACU_MSF_U_O_Foxhound_Marksman",
            "TACU_MSF_U_O_Foxhound_SMG_01",
            // Units (Indep - XOF CBRN Unit)
            "TACU_MSF_U_O_XOF_Rifleman_01",
            "TACU_MSF_U_O_XOF_Grenadier",
            "TACU_MSF_U_O_XOF_SMG_01",
            "TACU_MSF_U_O_XOF_SMG_02",
            "TACU_MSF_U_O_XOF_SMG_03",
            "TACU_MSF_U_O_XOF_Breacher",
            // Vehicles (Indep - Ground - Black))
            "TACU_MSF_V_I_MTVR_Ammo_Black",
            "TACU_MSF_V_I_MTVR_Refuel_Black",
            "TACU_MSF_V_I_MTVR_Repair_Black",
            "TACU_MSF_V_I_MTVR_Transport_Black",
            "TACU_MSF_V_I_Prowler_AT_Black",
            "TACU_MSF_V_I_Prowler_Black",
            "TACU_MSF_V_I_Prowler_HMG_Black",
            "TACU_MSF_V_I_Stryker_GL_Black",
            "TACU_MSF_V_I_Stryker_HMG_Black",
            // Vehicles (Indep - Ground - Desert)
            "TACU_MSF_V_I_MTVR_Ammo_Desert",
            "TACU_MSF_V_I_MTVR_Refuel_Desert",
            "TACU_MSF_V_I_MTVR_Repair_Desert",
            "TACU_MSF_V_I_MTVR_Transport_Desert",
            "TACU_MSF_V_I_Prowler_AT_Desert",
            "TACU_MSF_V_I_Prowler_Desert",
            "TACU_MSF_V_I_Prowler_HMG_Desert",
            // Vehicles (Indep - Ground - Wood)
            "TACU_MSF_V_I_MTVR_Ammo_Wood",
            "TACU_MSF_V_I_MTVR_Refuel_Wood",
            "TACU_MSF_V_I_MTVR_Repair_Wood",
            "TACU_MSF_V_I_MTVR_Transport_Wood",
            "TACU_MSF_V_I_Prowler_AT_Wood",
            "TACU_MSF_V_I_Prowler_Wood",
            "TACU_MSF_V_I_Prowler_HMG_Wood",
            // Vehicles (Indep - Air)
            "TACU_MSF_V_I_C130_Infantry",
            "TACU_MSF_V_I_C130_Vehicle",
            "TACU_MSF_V_I_Mi24",
            "TACU_MSF_V_I_UH60",
            "TACU_MSF_V_I_UH60_FFV",
            "TACU_MSF_V_I_UH60_Unarmed",
            "TACU_MSF_V_I_UH60_Unarmed_FFV",
            "TACU_MSF_V_I_UH60_Gunship",
            "TACU_MSF_V_I_V44_Infantry",
            "TACU_MSF_V_I_V44_Vehicle",
            // Vehicles (Opfor - Ground - Black)
            "TACU_MSF_V_O_MTVR_Ammo_Black",
            "TACU_MSF_V_O_MTVR_Refuel_Black",
            "TACU_MSF_V_O_MTVR_Repair_Black",
            "TACU_MSF_V_O_MTVR_Transport_Black",
            "TACU_MSF_V_O_Prowler_AT_Black",
            "TACU_MSF_V_O_Prowler_Black",
            "TACU_MSF_V_O_Prowler_HMG_Black",
            "TACU_MSF_V_O_Stryker_GL_Black",
            "TACU_MSF_V_O_Stryker_HMG_Black",
            // Vehicles (Opfor - Ground - Desert)
            "TACU_MSF_V_O_MTVR_Ammo_Desert",
            "TACU_MSF_V_O_MTVR_Refuel_Desert",
            "TACU_MSF_V_O_MTVR_Repair_Desert",
            "TACU_MSF_V_O_MTVR_Transport_Desert",
            "TACU_MSF_V_O_Prowler_AT_Desert",
            "TACU_MSF_V_O_Prowler_Desert",
            "TACU_MSF_V_O_Prowler_HMG_Desert",
            // Vehicles (Opfor - Ground - Wood)
            "TACU_MSF_V_O_MTVR_Ammo_Wood",
            "TACU_MSF_V_O_MTVR_Refuel_Wood",
            "TACU_MSF_V_O_MTVR_Repair_Wood",
            "TACU_MSF_V_O_MTVR_Transport_Wood",
            "TACU_MSF_V_O_Prowler_AT_Wood",
            "TACU_MSF_V_O_Prowler_Wood",
            "TACU_MSF_V_O_Prowler_HMG_Wood",
            // Vehicles (Opfor - Air)
            "TACU_MSF_V_O_C130_Infantry",
            "TACU_MSF_V_O_C130_Vehicle",
            "TACU_MSF_V_O_Mi24",
            "TACU_MSF_V_O_UH60",
            "TACU_MSF_V_O_UH60_FFV",
            "TACU_MSF_V_O_UH60_Unarmed",
            "TACU_MSF_V_O_UH60_Unarmed_FFV",
            "TACU_MSF_V_O_UH60_Gunship",
            "TACU_MSF_V_O_V44_Infantry",
            "TACU_MSF_V_O_V44_Vehicle"
        };
        weapons[] = {
            // Uniforms
            "TACU_MSF_Uniform_CBRN_Black",
            "TACU_MSF_Uniform_Combat_TigerBlack",
            "TACU_MSF_Uniform_Combat_TigerDesert",
            "TACU_MSF_Uniform_Combat_TigerWood",
            "TACU_MSF_Uniform_Combat_Fatigues_LS_Black",
            "TACU_MSF_Uniform_Combat_Fatigues_RS_Black",
            "TACU_MSF_Uniform_Combat_Fatigues_LS_Citrullus",
            "TACU_MSF_Uniform_Combat_Fatigues_RS_Citrullus",
            "TACU_MSF_Uniform_Combat_Fatigues_LS_DDPM",
            "TACU_MSF_Uniform_Combat_Fatigues_RS_DDPM",
            "TACU_MSF_Uniform_Combat_Fatigues_LS_Desert_Fox",
            "TACU_MSF_Uniform_Combat_Fatigues_RS_Desert_Fox",
            "TACU_MSF_Uniform_Combat_Fatigues_LS_Desert_Tiger",
            "TACU_MSF_Uniform_Combat_Fatigues_RS_Desert_Tiger",
            "TACU_MSF_Uniform_Combat_Fatigues_LS_DPM",
            "TACU_MSF_Uniform_Combat_Fatigues_RS_DPM",
            "TACU_MSF_Uniform_Combat_Fatigues_LS_German_Flecktarn",
            "TACU_MSF_Uniform_Combat_Fatigues_RS_German_Flecktarn",
            "TACU_MSF_Uniform_Combat_Fatigues_LS_Horsky",
            "TACU_MSF_Uniform_Combat_Fatigues_RS_Horsky",
            "TACU_MSF_Uniform_Combat_Fatigues_LS_Jungle_Tiger",
            "TACU_MSF_Uniform_Combat_Fatigues_RS_Jungle_Tiger",
            "TACU_MSF_Uniform_Combat_Fatigues_LS_Khaki",
            "TACU_MSF_Uniform_Combat_Fatigues_RS_Khaki",
            "TACU_MSF_Uniform_Combat_Fatigues_LS_Letni",
            "TACU_MSF_Uniform_Combat_Fatigues_RS_Letni",
            "TACU_MSF_Uniform_Combat_Fatigues_LS_Multicam",
            "TACU_MSF_Uniform_Combat_Fatigues_RS_Multicam",
            "TACU_MSF_Uniform_Combat_Fatigues_LS_Olive",
            "TACU_MSF_Uniform_Combat_Fatigues_RS_Olive",
            "TACU_MSF_Uniform_Combat_Fatigues_LS_Rhodesian_Bushstroke",
            "TACU_MSF_Uniform_Combat_Fatigues_RS_Rhodesian_Bushstroke",
            "TACU_MSF_Uniform_Combat_Fatigues_LS_Type3_Flecktarn",
            "TACU_MSF_Uniform_Combat_Fatigues_RS_Type3_Flecktarn",
            "TACU_MSF_Uniform_Combat_Fatigues_LS_Urban_Tiger",
            "TACU_MSF_Uniform_Combat_Fatigues_RS_Urban_Tiger",
            "TACU_MSF_Uniform_Combat_Fatigues_LS_Wetworks",
            "TACU_MSF_Uniform_Combat_Fatigues_RS_Wetworks",
            "TACU_MSF_Uniform_Combat_Fatigues_LS_Woodland",
            "TACU_MSF_Uniform_Combat_Fatigues_RS_Woodland",
            "TACU_MSF_Uniform_Prisoner_Outfit_Orange_Clean",
            "TACU_MSF_Uniform_Prisoner_Outfit_Orange_Dirty",
            "TACU_MSF_Uniform_Prisoner_Outfit_Orange_Muddy",
            "TACU_MSF_Uniform_Prisoner_Outfit_Blue_Clean",
            "TACU_MSF_Uniform_Prisoner_Outfit_Blue_Dirty",
            "TACU_MSF_Uniform_Prisoner_Outfit_Blue_Muddy",
            "TACU_MSF_Uniform_Prisoner_Outfit_Olive_Clean",
            "TACU_MSF_Uniform_Prisoner_Outfit_Olive_Dirty",
            "TACU_MSF_Uniform_Prisoner_Outfit_Olive_Muddy",
            // Vests
            "TACU_MSF_Vest_HeavyPlateCarrier_Black",
            "TACU_MSF_Vest_HeavyPlateCarrier_Coyote",
            "TACU_MSF_Vest_HeavyPlateCarrier_Green",
            "TACU_MSF_Vest_PlateCarrier_Black",
            "TACU_MSF_Vest_PlateCarrier_Coyote",
            "TACU_MSF_Vest_PlateCarrier_Green",
            "TACU_MSF_Vest_ChestRig_Green",
            "TACU_MSF_Vest_ChestRig_Black",
            "TACU_MSF_Vest_ChestRig_Khaki",
            // Weapons
            "TACU_MSF_W_CZ_BREN2_8in_Stealth",
            "TACU_MSF_W_CZ_BREN2_11in",
            "TACU_MSF_W_CZ_BREN2_11in_GL",
            "TACU_MSF_W_HK416_Black",
            "TACU_MSF_W_HK416GL_Black",
            "TACU_MSF_W_HK416_CQC_Black",
            "TACU_MSF_W_HK416GL_CQC_Black",
            "TACU_MSF_W_HK417DMR_Black",
            "TACU_MSF_W_M1014_Entry",
            "TACU_MSF_W_M110_Stealth",
            "TACU_MSF_W_M200_Intervention",
            "TACU_MSF_W_M27_Grip",
            "TACU_MSF_W_Mk23_SOCOM",
            "TACU_MSF_W_Mk23_SOCOM_Stealth",
            "TACU_MSF_W_MP7A1",
            "TACU_MSF_W_MP7A1_Stealth",
            "TACU_MSF_W_P90",
            "TACU_MSF_W_Promet_Black",
            "TACU_MSF_W_PrometGL_Black",
            "TACU_MSF_W_PrometDMR_Black",
            "TACU_MSF_W_PrometSG_Black",
            "TACU_MSF_W_Stoner99LMG"
        };
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {"tacu_main"};
        author = ECSTRING(main,Author);
        authors[] = {"Kresky"};
        VERSION_CONFIG;
    };
};

#include "CfgFactionClasses.hpp"
#include "CfgGlasses.hpp"
#include "CfgGroups.hpp"
#include "CfgUnitInsignia.hpp"
#include "CfgVehicles.hpp"
#include "CfgWeapons.hpp"
