class TACU_SouthAfricanNames {
    class FirstNames {
        bongani = "Bongani";
        david = "David";
        hendrik = "Hendrik";
        isaac = "Isaac";
        johan = "Johan";
        johannes = "Johannes";
        john = "John";
        matome = "Matome";
        michael = "Michael";
        nkosinathi = "Nkosinathi";
        petrus = "Petrus";
        pieter = "Pieter";
        sello = "Sello";
        sibusiso = "Sibusiso";
        sifiso = "Sifiso";
        sipho = "Sipho";
        siyabonga = "Siyabonga";
        themba = "Themba";
        thulani = "Thulani";
        vusi = "Vusi";
        xolani = "Xolani";
    };
    class LastNames {
        botha = "Botha";
        chauke = "Chauke";
        dlamini = "Dlamini";
        govender = "Govender";
        gumede = "Gumede";
        khoza = "Khoza";
        khumalo = "Khumalo";
        mahlangu = "Mahlangu";
        mokoena = "Mokoena";
        mthembu = "Mthembu";
        ngcobo = "Ngcobo";
        nkosi = "Nkosi";
        ntuli = "Ntuli";
        pillay = "Pillay";
        pretorius = "Pretorius";
        radebe = "Radebe";
        sithole = "Sithole";
        smith = "Smith";
        vandermerwe = "Van Der Merwe";
        vanwyk = "Van Wyk";
        zulu = "Zulu";
    };
};
