class CfgVehicles {
    #include "Vehicles\Base.hpp"

    #ifdef DEBUG_MODE_FULL
        #include "Vehicles\Test_Unit.hpp"
    #endif

    // Vehicles - Using ACE Realistic names
    #include "Vehicles\AH6_Little_Bird.hpp"
    #include "Vehicles\AW101.hpp"
    #include "Vehicles\Backpacks.hpp"
    #include "Vehicles\Badger_IFV.hpp"
    #include "Vehicles\Bardelas.hpp"
    #include "Vehicles\Chinook_Armed.hpp"
    #include "Vehicles\Chinook_Unarmed.hpp"
    #include "Vehicles\Fennek_GMG.hpp"
    #include "Vehicles\Fennek_HMG.hpp"
    #include "Vehicles\Fennek_Unarmed.hpp"
    #include "Vehicles\FV510_Warrior.hpp"
    #include "Vehicles\Ghosthawk.hpp"
    #include "Vehicles\HEMTT.hpp"
    #include "Vehicles\Jeep_Wrangler_AT.hpp"
    #include "Vehicles\Jeep_Wrangler_LMG.hpp"
    #include "Vehicles\Jeep_Wrangler_Unarmed.hpp"
    #include "Vehicles\Kamaz.hpp"
    #include "Vehicles\Kamaz_Covered.hpp"
    #include "Vehicles\Kamaz_MRL.hpp"
    #include "Vehicles\Kamaz_ZU23.hpp"
    #include "Vehicles\Karatel_GMG.hpp"
    #include "Vehicles\Karatel_HMG.hpp"
    #include "Vehicles\Karatel_Unarmed.hpp"
    #include "Vehicles\Kasatka_Armed.hpp"
    #include "Vehicles\Kasatka_Unarmed.hpp"
    #include "Vehicles\Kasatka_UP.hpp"
    #include "Vehicles\Kasatka_UP_Armed.hpp"
    #include "Vehicles\Leopard_2SG.hpp"
    #include "Vehicles\LSV_MKII_Armed.hpp"
    #include "Vehicles\LSV_MKII_Armed_AT.hpp"
    #include "Vehicles\LSV_MKII_Unarmed.hpp"
    #include "Vehicles\MATV_GMG.hpp"
    #include "Vehicles\MATV_HMG.hpp"
    #include "Vehicles\MATV_Unarmed.hpp"
    #include "Vehicles\Namer.hpp"
    #include "Vehicles\Nemmera.hpp"
    #include "Vehicles\Offroad.hpp"
    #include "Vehicles\Offroad_Armed.hpp"
    #include "Vehicles\Offroad_Armed_AT.hpp"
    #include "Vehicles\Offroad_Armed_AT_UP.hpp"
    #include "Vehicles\Offroad_Armed_UP.hpp"
    #include "Vehicles\Offroad_Covered.hpp"
    #include "Vehicles\Offroad_UP.hpp"
    #include "Vehicles\Otokar_ARMA_Armed.hpp"
    #include "Vehicles\Otokar_ARMA_HMG.hpp"
    #include "Vehicles\Otokar_ARMA_Unarmed.hpp"
    #include "Vehicles\Pandur.hpp"
    #include "Vehicles\Polaris_Armed.hpp"
    #include "Vehicles\Polaris_Armed_AT.hpp"
    #include "Vehicles\Polaris_Unarmed.hpp"
    #include "Vehicles\RAH66_Comanche.hpp"
    #include "Vehicles\Rooikat.hpp"
    #include "Vehicles\Rooikat_UP.hpp"
    #include "Vehicles\Speedboat_Minigun.hpp"
    #include "Vehicles\Truck.hpp"
    #include "Vehicles\Typhoon.hpp"
    #include "Vehicles\Typhoon_Covered.hpp"
    #include "Vehicles\Van_Cargo.hpp"
    #include "Vehicles\Van_Transport.hpp"
    #include "Vehicles\Wiesel_Armed.hpp"
    #include "Vehicles\Wiesel_Armed_AT.hpp"
    #include "Vehicles\Wildcat_Armed.hpp"
    #include "Vehicles\Wildcat_Unarmed.hpp"

    // Wearables
    #include "Vehicles\Wearables\BAF_Helmets.hpp"
    #include "Vehicles\Wearables\BAF_Vests.hpp"
    #include "Vehicles\Wearables\Cartel_Uniforms.hpp"
    #include "Vehicles\Wearables\Police_Helmets.hpp"
    #include "Vehicles\Wearables\Police_Uniforms.hpp"
    #include "Vehicles\Wearables\Police_Vests.hpp"
    #include "Vehicles\Wearables\Prisoner_Uniforms.hpp"
    #include "Vehicles\Wearables\SevenRings_Vests.hpp"
    #include "Vehicles\Wearables\South_Africa_Helmets.hpp"
    #include "Vehicles\Wearables\South_Africa_Uniforms.hpp"
    #include "Vehicles\Wearables\Vanguard_Vests.hpp"

    // Weapons
    #include "Vehicles\Rifles.hpp"

    // Turrets
    #include "Vehicles\Turrets.hpp"
    #include "Vehicles\CUP_Turrets.hpp"
};
