name = "TAC Units"
prefix = "tacu"
author = "TAC Units Team"

[files]
include = [
    "mod.cpp",
    "README.md",
    "logo_tacu_ca.paa",
    "logo_tacu_small_ca.paa"
]

[version]
git_hash = 0

[hemtt.config]
preset = "Hemtt"

[hemtt.release]
folder = "tac_units"
