class TACU_Territorial_Militia_V_O_Offroad_Unarmed_Woodland;
class TACU_Territorial_Defence_V_O_Offroad_Unarmed_Woodland: TACU_Territorial_Militia_V_O_Offroad_Unarmed_Woodland {
    MACRO_WOODLAND_VEHICLES;
};

class TACU_Territorial_Militia_V_O_Offroad_M2_Woodland;
class TACU_Territorial_Defence_V_O_Offroad_M2_Woodland: TACU_Territorial_Militia_V_O_Offroad_M2_Woodland {
    MACRO_WOODLAND_VEHICLES;
};

class TACU_Territorial_Militia_V_O_Truck_Woodland;
class TACU_Territorial_Defence_V_O_Truck_Woodland: TACU_Territorial_Militia_V_O_Truck_Woodland {
    MACRO_WOODLAND_VEHICLES;
};

class TACU_Territorial_Militia_V_O_Kamaz_Transport_Woodland;
class TACU_Territorial_Defence_V_O_Kamaz_Transport_Woodland: TACU_Territorial_Militia_V_O_Kamaz_Transport_Woodland {
    MACRO_WOODLAND_VEHICLES;
};

class TACU_Territorial_Militia_V_O_Kamaz_Woodland;
class TACU_Territorial_Defence_V_O_Kamaz_Woodland: TACU_Territorial_Militia_V_O_Kamaz_Woodland {
    MACRO_WOODLAND_VEHICLES;
};
