#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            // Blufor - Units
            "TACU_UN_Autumn_U_B_Rifleman",
            "TACU_UN_Autumn_U_B_Demolitions",
            "TACU_UN_Autumn_U_B_Grenadier",
            "TACU_UN_Autumn_U_B_Marksman",
            "TACU_UN_Autumn_U_B_Teamleader",
            "TACU_UN_Autumn_U_B_Autorifleman",
            "TACU_UN_Autumn_U_B_Machinegunner",
            "TACU_UN_Autumn_U_B_Medic",
            "TACU_UN_Autumn_U_B_AT",
            "TACU_UN_Autumn_U_B_Driver",
            "TACU_UN_Autumn_U_B_Pilot",
            "TACU_UN_Urban_U_B_Rifleman",
            "TACU_UN_Urban_U_B_Demolitions",
            "TACU_UN_Urban_U_B_Grenadier",
            "TACU_UN_Urban_U_B_Marksman",
            "TACU_UN_Urban_U_B_Teamleader",
            "TACU_UN_Urban_U_B_Autorifleman",
            "TACU_UN_Urban_U_B_Machinegunner",
            "TACU_UN_Urban_U_B_Medic",
            "TACU_UN_Urban_U_B_AT",
            "TACU_UN_Urban_U_B_Driver",
            "TACU_UN_Woodland_U_B_Rifleman",
            "TACU_UN_Woodland_U_B_Demolitions",
            "TACU_UN_Woodland_U_B_Grenadier",
            "TACU_UN_Woodland_U_B_Marksman",
            "TACU_UN_Woodland_U_B_Teamleader",
            "TACU_UN_Woodland_U_B_Autorifleman",
            "TACU_UN_Woodland_U_B_Machinegunner",
            "TACU_UN_Woodland_U_B_Medic",
            "TACU_UN_Woodland_U_B_AT",
            "TACU_UN_Woodland_U_B_Driver",
            // Blufor - Vehicles
            "TACU_UN_V_B_Mohawk",
            "TACU_UN_V_B_Leopard",
            "TACU_UN_Autumn_V_B_Marshall",
            "TACU_UN_Autumn_V_B_Marid_HMG",
            "TACU_UN_Autumn_V_B_Marid_Unarmed",
            "TACU_UN_Autumn_V_B_HEMTT_Mover",
            "TACU_UN_Autumn_V_B_HEMTT_Ammo",
            "TACU_UN_Autumn_V_B_HEMTT_Container",
            "TACU_UN_Autumn_V_B_HEMTT_Fuel",
            "TACU_UN_Autumn_V_B_HEMTT_Medical",
            "TACU_UN_Autumn_V_B_HEMTT_Repair",
            "TACU_UN_Autumn_V_B_HEMTT_Transport",
            "TACU_UN_Autumn_V_B_HEMTT_Transport_Covered",
            "TACU_UN_Autumn_V_B_MATV",
            "TACU_UN_Autumn_V_B_Offroad",
            "TACU_UN_Autumn_V_B_Offroad_UP",
            "TACU_UN_Urban_V_B_Marshall",
            "TACU_UN_Urban_V_B_Marid_HMG",
            "TACU_UN_Urban_V_B_Marid_Unarmed",
            "TACU_UN_Urban_V_B_HEMTT_Mover",
            "TACU_UN_Urban_V_B_HEMTT_Ammo",
            "TACU_UN_Urban_V_B_HEMTT_Container",
            "TACU_UN_Urban_V_B_HEMTT_Fuel",
            "TACU_UN_Urban_V_B_HEMTT_Medical",
            "TACU_UN_Urban_V_B_HEMTT_Repair",
            "TACU_UN_Urban_V_B_HEMTT_Transport",
            "TACU_UN_Urban_V_B_HEMTT_Transport_Covered",
            "TACU_UN_Urban_V_B_MATV",
            "TACU_UN_Urban_V_B_Offroad",
            "TACU_UN_Urban_V_B_Offroad_UP",
            "TACU_UN_Woodland_V_B_Marshall",
            "TACU_UN_Woodland_V_B_Marid_HMG",
            "TACU_UN_Woodland_V_B_Marid_Unarmed",
            "TACU_UN_Woodland_V_B_HEMTT_Mover",
            "TACU_UN_Woodland_V_B_HEMTT_Ammo",
            "TACU_UN_Woodland_V_B_HEMTT_Container",
            "TACU_UN_Woodland_V_B_HEMTT_Fuel",
            "TACU_UN_Woodland_V_B_HEMTT_Medical",
            "TACU_UN_Woodland_V_B_HEMTT_Repair",
            "TACU_UN_Woodland_V_B_HEMTT_Transport",
            "TACU_UN_Woodland_V_B_HEMTT_Transport_Covered",
            "TACU_UN_Woodland_V_B_MATV",
            "TACU_UN_Woodland_V_B_Offroad",
            "TACU_UN_Woodland_V_B_Offroad_UP",
            // Independent - Units
            "TACU_UN_Autumn_U_I_Rifleman",
            "TACU_UN_Autumn_U_I_Demolitions",
            "TACU_UN_Autumn_U_I_Grenadier",
            "TACU_UN_Autumn_U_I_Marksman",
            "TACU_UN_Autumn_U_I_Teamleader",
            "TACU_UN_Autumn_U_I_Autorifleman",
            "TACU_UN_Autumn_U_I_Machinegunner",
            "TACU_UN_Autumn_U_I_Medic",
            "TACU_UN_Autumn_U_I_AT",
            "TACU_UN_Autumn_U_I_Driver",
            "TACU_UN_Autumn_U_I_Pilot",
            "TACU_UN_Urban_U_I_Rifleman",
            "TACU_UN_Urban_U_I_Demolitions",
            "TACU_UN_Urban_U_I_Grenadier",
            "TACU_UN_Urban_U_I_Marksman",
            "TACU_UN_Urban_U_I_Teamleader",
            "TACU_UN_Urban_U_I_Autorifleman",
            "TACU_UN_Urban_U_I_Machinegunner",
            "TACU_UN_Urban_U_I_Medic",
            "TACU_UN_Urban_U_I_AT",
            "TACU_UN_Urban_U_I_Driver",
            "TACU_UN_Woodland_U_I_Rifleman",
            "TACU_UN_Woodland_U_I_Demolitions",
            "TACU_UN_Woodland_U_I_Grenadier",
            "TACU_UN_Woodland_U_I_Marksman",
            "TACU_UN_Woodland_U_I_Teamleader",
            "TACU_UN_Woodland_U_I_Autorifleman",
            "TACU_UN_Woodland_U_I_Machinegunner",
            "TACU_UN_Woodland_U_I_Medic",
            "TACU_UN_Woodland_U_I_AT",
            "TACU_UN_Woodland_U_I_Driver",
            // Independent - Vehicles
            "TACU_UN_V_I_Mohawk",
            "TACU_UN_V_I_Leopard",
            "TACU_UN_Autumn_V_I_Marshall",
            "TACU_UN_Autumn_V_I_Marid_HMG",
            "TACU_UN_Autumn_V_I_Marid_Unarmed",
            "TACU_UN_Autumn_V_I_HEMTT_Mover",
            "TACU_UN_Autumn_V_I_HEMTT_Ammo",
            "TACU_UN_Autumn_V_I_HEMTT_Container",
            "TACU_UN_Autumn_V_I_HEMTT_Fuel",
            "TACU_UN_Autumn_V_I_HEMTT_Medical",
            "TACU_UN_Autumn_V_I_HEMTT_Repair",
            "TACU_UN_Autumn_V_I_HEMTT_Transport",
            "TACU_UN_Autumn_V_I_HEMTT_Transport_Covered",
            "TACU_UN_Autumn_V_I_MATV",
            "TACU_UN_Autumn_V_I_Offroad",
            "TACU_UN_Autumn_V_I_Offroad_UP",
            "TACU_UN_Urban_V_I_Marshall",
            "TACU_UN_Urban_V_I_Marid_HMG",
            "TACU_UN_Urban_V_I_Marid_Unarmed",
            "TACU_UN_Urban_V_I_HEMTT_Mover",
            "TACU_UN_Urban_V_I_HEMTT_Ammo",
            "TACU_UN_Urban_V_I_HEMTT_Container",
            "TACU_UN_Urban_V_I_HEMTT_Fuel",
            "TACU_UN_Urban_V_I_HEMTT_Medical",
            "TACU_UN_Urban_V_I_HEMTT_Repair",
            "TACU_UN_Urban_V_I_HEMTT_Transport",
            "TACU_UN_Urban_V_I_HEMTT_Transport_Covered",
            "TACU_UN_Urban_V_I_MATV",
            "TACU_UN_Urban_V_I_Offroad",
            "TACU_UN_Urban_V_I_Offroad_UP",
            "TACU_UN_Woodland_V_I_Marshall",
            "TACU_UN_Woodland_V_I_Marid_HMG",
            "TACU_UN_Woodland_V_I_Marid_Unarmed",
            "TACU_UN_Woodland_V_I_HEMTT_Mover",
            "TACU_UN_Woodland_V_I_HEMTT_Ammo",
            "TACU_UN_Woodland_V_I_HEMTT_Container",
            "TACU_UN_Woodland_V_I_HEMTT_Fuel",
            "TACU_UN_Woodland_V_I_HEMTT_Medical",
            "TACU_UN_Woodland_V_I_HEMTT_Repair",
            "TACU_UN_Woodland_V_I_HEMTT_Transport",
            "TACU_UN_Woodland_V_I_HEMTT_Transport_Covered",
            "TACU_UN_Woodland_V_I_MATV",
            "TACU_UN_Woodland_V_I_Offroad",
            "TACU_UN_Woodland_V_I_Offroad_UP",
        };
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {"tacu_main", "tacu_assets"};
        author = ECSTRING(main,Author);
        authors[] = {"Mike"};
        url = ECSTRING(main,URL);
        VERSION_CONFIG;
    };
};

#include "CfgFactionClasses.hpp"
#include "CfgGroups.hpp"
#include "CfgVehicles.hpp"
#include "CfgWeapons.hpp"
