#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            // Backpacks
            "TACU_African_South_B_Medic",
            "TACU_African_South_B_Demolitions",
            "TACU_African_South_B_MG",
            "TACU_African_South_B_AT",
            "TACU_African_South_B_AP",
            "TACU_African_South_B_AA",
            // Blufor Units
            "TACU_African_South_U_B_Rifleman",
            "TACU_African_South_U_B_CQB",
            "TACU_African_South_U_B_Medic",
            "TACU_African_South_U_B_Demolitions",
            "TACU_African_South_U_B_Grenadier",
            "TACU_African_South_U_B_Autorifleman",
            "TACU_African_South_U_B_Machinegunner",
            "TACU_African_South_U_B_Marksman",
            "TACU_African_South_U_B_TL",
            "TACU_African_South_U_B_AT",
            "TACU_African_South_U_B_AP",
            "TACU_African_South_U_B_AA",
            "TACU_African_South_U_B_Sniper",
            "TACU_African_South_U_B_Spotter",
            "TACU_African_South_U_B_Pilot",
            // Blufor Vehicles
            "TACU_African_South_V_B_Assault_Boat",
            "TACU_African_South_V_B_Speedboat_Minigun",
            "TACU_African_South_V_B_Fennek",
            "TACU_African_South_V_B_Fennek_Tan",
            "TACU_African_South_V_B_Fennek_HMG",
            "TACU_African_South_V_B_Fennek_HMG_Tan",
            "TACU_African_South_V_B_Fennek_GMG",
            "TACU_African_South_V_B_Fennek_GMG_Tan",
            "TACU_African_South_V_B_Polaris",
            "TACU_African_South_V_B_Polaris_Tan",
            "TACU_African_South_V_B_Polaris_Armed",
            "TACU_African_South_V_B_Polaris_Armed_Tan",
            "TACU_African_South_V_B_Polaris_AT",
            "TACU_African_South_V_B_Polaris_AT_Tan",
            "TACU_African_South_V_B_Kamaz",
            "TACU_African_South_V_B_Kamaz_Tan",
            "TACU_African_South_V_B_Kamaz_Covered",
            "TACU_African_South_V_B_Kamaz_Covered_Tan",
            "TACU_African_South_V_B_Merlin",
            "TACU_African_South_V_B_Badger",
            "TACU_African_South_V_B_Badger_SLAT",
            "TACU_African_South_V_B_Badger_Tan",
            "TACU_African_South_V_B_Badger_Tan_SLAT",
            "TACU_African_South_V_B_Rooikat",
            "TACU_African_South_V_B_Rooikat_SLAT",
            "TACU_African_South_V_B_Rooikat_Tan",
            "TACU_African_South_V_B_Rooikat_Tan_SLAT",
            "TACU_African_South_V_B_Rooikat_UP",
            "TACU_African_South_V_B_Rooikat_UP_Tan",
            "TACU_African_South_V_B_Leopard",
            "TACU_African_South_V_B_Leopard_Tan",
            "TACU_African_South_V_B_Wildcat",
            "TACU_African_South_V_B_Wildcat_Unarmed",
            // Blufor Turrets
            "TACU_African_South_V_B_MK6",
            "TACU_African_South_V_B_HMG_50",
            "TACU_African_South_V_B_HMG_50_Low",
            "TACU_African_South_V_B_Mini_Spike_Green",
            "TACU_African_South_V_B_D30",
            "TACU_African_South_V_B_FIM92",
            "TACU_African_South_V_B_ZU23",
            // Independent Units
            "TACU_African_South_U_I_Rifleman",
            "TACU_African_South_U_I_CQB",
            "TACU_African_South_U_I_Medic",
            "TACU_African_South_U_I_Demolitions",
            "TACU_African_South_U_I_Grenadier",
            "TACU_African_South_U_I_Autorifleman",
            "TACU_African_South_U_I_Machinegunner",
            "TACU_African_South_U_I_Marksman",
            "TACU_African_South_U_I_TL",
            "TACU_African_South_U_I_AT",
            "TACU_African_South_U_I_AP",
            "TACU_African_South_U_I_AA",
            "TACU_African_South_U_I_Sniper",
            "TACU_African_South_U_I_Spotter",
            "TACU_African_South_U_I_Pilot",
            // Independent Vehicles
            "TACU_African_South_V_I_Assault_Boat",
            "TACU_African_South_V_I_Speedboat_Minigun",
            "TACU_African_South_V_I_Fennek",
            "TACU_African_South_V_I_Fennek_Tan",
            "TACU_African_South_V_I_Fennek_HMG",
            "TACU_African_South_V_I_Fennek_HMG_Tan",
            "TACU_African_South_V_I_Fennek_GMG",
            "TACU_African_South_V_I_Fennek_GMG_Tan",
            "TACU_African_South_V_I_Polaris",
            "TACU_African_South_V_I_Polaris_Tan",
            "TACU_African_South_V_I_Polaris_Armed",
            "TACU_African_South_V_I_Polaris_Armed_Tan",
            "TACU_African_South_V_I_Polaris_AT",
            "TACU_African_South_V_I_Polaris_AT_Tan",
            "TACU_African_South_V_I_Kamaz",
            "TACU_African_South_V_I_Kamaz_Tan",
            "TACU_African_South_V_I_Kamaz_Covered",
            "TACU_African_South_V_I_Kamaz_Covered_Tan",
            "TACU_African_South_V_I_Merlin",
            "TACU_African_South_V_I_Badger",
            "TACU_African_South_V_I_Badger_SLAT",
            "TACU_African_South_V_I_Badger_Tan",
            "TACU_African_South_V_I_Badger_Tan_SLAT",
            "TACU_African_South_V_I_Rooikat",
            "TACU_African_South_V_I_Rooikat_SLAT",
            "TACU_African_South_V_I_Rooikat_Tan",
            "TACU_African_South_V_I_Rooikat_Tan_SLAT",
            "TACU_African_South_V_I_Rooikat_UP",
            "TACU_African_South_V_I_Rooikat_UP_Tan",
            "TACU_African_South_V_I_Leopard",
            "TACU_African_South_V_I_Leopard_Tan",
            "TACU_African_South_V_I_Wildcat",
            "TACU_African_South_V_I_Wildcat_Unarmed",
            // Independent Turrets
            "TACU_African_South_V_I_MK6",
            "TACU_African_South_V_I_HMG_50",
            "TACU_African_South_V_I_HMG_50_Low",
            "TACU_African_South_V_I_Mini_Spike_Green",
            "TACU_African_South_V_I_D30",
            "TACU_African_South_V_I_FIM92",
            "TACU_African_South_V_I_ZU23",
            // Opfor Units
            "TACU_African_South_U_O_Rifleman",
            "TACU_African_South_U_O_CQB",
            "TACU_African_South_U_O_Medic",
            "TACU_African_South_U_O_Demolitions",
            "TACU_African_South_U_O_Grenadier",
            "TACU_African_South_U_O_Autorifleman",
            "TACU_African_South_U_O_Machinegunner",
            "TACU_African_South_U_O_Marksman",
            "TACU_African_South_U_O_TL",
            "TACU_African_South_U_O_AT",
            "TACU_African_South_U_O_AP",
            "TACU_African_South_U_O_AA",
            "TACU_African_South_U_O_Sniper",
            "TACU_African_South_U_O_Spotter",
            "TACU_African_South_U_O_Pilot",
            // Opfor Vehicles
            "TACU_African_South_V_O_Assault_Boat",
            "TACU_African_South_V_O_Speedboat_Minigun",
            "TACU_African_South_V_O_Fennek",
            "TACU_African_South_V_O_Fennek_Tan",
            "TACU_African_South_V_O_Fennek_HMG",
            "TACU_African_South_V_O_Fennek_HMG_Tan",
            "TACU_African_South_V_O_Fennek_GMG",
            "TACU_African_South_V_O_Fennek_GMG_Tan",
            "TACU_African_South_V_O_Polaris",
            "TACU_African_South_V_O_Polaris_Tan",
            "TACU_African_South_V_O_Polaris_Armed",
            "TACU_African_South_V_O_Polaris_Armed_Tan",
            "TACU_African_South_V_O_Polaris_AT",
            "TACU_African_South_V_O_Polaris_AT_Tan",
            "TACU_African_South_V_O_Kamaz",
            "TACU_African_South_V_O_Kamaz_Tan",
            "TACU_African_South_V_O_Kamaz_Covered",
            "TACU_African_South_V_O_Kamaz_Covered_Tan",
            "TACU_African_South_V_O_Merlin",
            "TACU_African_South_V_O_Badger",
            "TACU_African_South_V_O_Badger_SLAT",
            "TACU_African_South_V_O_Badger_Tan",
            "TACU_African_South_V_O_Badger_Tan_SLAT",
            "TACU_African_South_V_O_Rooikat",
            "TACU_African_South_V_O_Rooikat_SLAT",
            "TACU_African_South_V_O_Rooikat_Tan",
            "TACU_African_South_V_O_Rooikat_Tan_SLAT",
            "TACU_African_South_V_O_Rooikat_UP",
            "TACU_African_South_V_O_Rooikat_UP_Tan",
            "TACU_African_South_V_O_Leopard",
            "TACU_African_South_V_O_Leopard_Tan",
            "TACU_African_South_V_O_Wildcat",
            "TACU_African_South_V_O_Wildcat_Unarmed",
            // Opfor Turrets
            "TACU_African_South_V_O_MK6",
            "TACU_African_South_V_O_HMG_50",
            "TACU_African_South_V_O_HMG_50_Low",
            "TACU_African_South_V_O_Mini_Spike_Green",
            "TACU_African_South_V_O_D30",
            "TACU_African_South_V_O_FIM92",
            "TACU_African_South_V_O_ZU23"
        };
        weapons[] = {
            "TACU_African_South_W_Green_XMS",
            "TACU_African_South_W_Green_XMS_GL",
            "TACU_African_South_W_Green_XMS_SG",
            "TACU_African_South_W_Green_SW",
            "TACU_African_South_W_SLR",
            "TACU_African_South_W_SPW",
            "TACU_African_South_W_Green_M200",
            "TACU_African_South_W_Green_FNX"
        };
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {
            "tacu_main",
            "tacu_assets",
            "CUP_Weapons_LoadOrder"
        };
        skipWhenMissingDependencies = 1;
        author = ECSTRING(main,Author);
        authors[] = {"Mike"};
        url = ECSTRING(main,URL);
        VERSION_CONFIG;
    };
};

#include "CfgFactionClasses.hpp"
#include "CfgGroups.hpp"
#include "CfgWeapons.hpp"
#include "CfgVehicles.hpp"
