#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {
            // Units
            "TACU_Assets_TestUnit",
            // Vehicles
            "TACU_AH6_LittleBird_Base",
            "TACU_Assault_Boat_Base",
            "TACU_Badger_IFV_Base",
            "TACU_Bardelas_Base",
            "TACU_BM2T_Iskatel_Base",
            "TACU_BM2T_Stalker_Base",
            "TACU_Cargo_Van_Base",
            "TACU_Chinook_Armed_Base",
            "TACU_Chinook_Unarmed_Base",
            "TACU_Fennek_GMG_Base",
            "TACU_Fennek_HMG_Base",
            "TACU_Fennek_Unarmed_Base",
            "TACU_FV510_Warrior_Base",
            "TACU_GhostHawk_Base",
            "TACU_HEMTT_Base",
            "TACU_HEMTT_Covered_Base",
            "TACU_Jeep_Wrangler_AT_Base",
            "TACU_Jeep_Wrangler_LMG_Base",
            "TACU_Jeep_Wrangler_Unarmed_Base",
            "TACU_Kamaz_Base",
            "TACU_Kamaz_Covered_Base",
            "TACU_Kamaz_MRL_Base",
            "TACU_Kamaz_ZU23_Base",
            "TACU_Karatel_GMG_Base",
            "TACU_Karatel_HMG_Base",
            "TACU_Karatel_Unarmed_Base",
            "TACU_Kasatka_Armed_Armoured_Base",
            "TACU_Kasatka_Armed_Base",
            "TACU_Kasatka_Unarmed_Armoured_Base",
            "TACU_Kasatka_Unarmed_Base",
            "TACU_Leopard_2SG_Base",
            "TACU_LSV_MKII_Armed_AT_Base",
            "TACU_LSV_MKII_Armed_Base",
            "TACU_LSV_MKII_Base",
            "TACU_MATV_GMG_Base",
            "TACU_MATV_HMG_Base",
            "TACU_MATV_Unarmed_Base",
            "TACU_Merlin_Base",
            "TACU_Namer_Base",
            "TACU_Nemmera_Base",
            "TACU_Offroad_Armed_AT_Base",
            "TACU_Offroad_Armed_AT_UP_Base",
            "TACU_Offroad_Armed_M2_Base",
            "TACU_Offroad_Armed_M2_UP_Base",
            "TACU_Offroad_Covered_Base",
            "TACU_Offroad_Unarmed_Base",
            "TACU_Offroad_Unarmed_UP_Base",
            "TACU_Otokar_ARMA_Armed_Base",
            "TACU_Otokar_ARMA_HMG_Base",
            "TACU_Otokar_ARMA_Unarmed_Base",
            "TACU_Pandur_Base",
            "TACU_Polaris_Armed_AT_Base",
            "TACU_Polaris_Armed_Base",
            "TACU_Polaris_Unarmed_Base",
            "TACU_RAH66_Comanche_Base",
            "TACU_Ram1500_HMG_Base",
            "TACU_Ram1500_MMG_Base",
            "TACU_Ram1500_Unarmed_Base",
            "TACU_Rooikat_Base",
            "TACU_Rooikat_UP_Base",
            "TACU_Speedboat_Minigun_Base",
            "TACU_Taru_Transport_Base",
            "TACU_Tigris_Base",
            "TACU_Transport_Van_Base",
            "TACU_Transport_Van_Base",
            "TACU_Truck_Base",
            "TACU_Typhoon_Base",
            "TACU_Typhoon_Covered_Base",
            "TACU_Typhoon_Device_Base",
            "TACU_Wiesel_Armed_AT_Base",
            "TACU_Wiesel_Armed_Base",
            "TACU_Wildcat_Armed_Base",
            "TACU_Wildcat_Base",
            // CUP Vehicles
            "TACU_BMP2_Base",
            "TACU_BMP2K_Base",
            "TACU_BMP3_Base",
            "TACU_BRDM2_Base",
            "TACU_BTR60_Base",
            "TACU_BTR80_Base",
            "TACU_BTR80A_Base",
            "TACU_BTR90_Base",
            "TACU_BTR90_HQ_Base",
            "TACU_Hilux_Armored_Base",
            "TACU_Hilux_Armored_BMP1_Base",
            "TACU_Hilux_Armored_BTR60_Base",
            "TACU_Hilux_Base",
            "TACU_Hilux_BMP1_Base",
            "TACU_Hilux_BTR60_Base",
            "TACU_HMMWV_M2_Base",
            "TACU_Leopard_1_Base",
            "TACU_M113A1_Base",
            "TACU_M113A3_Base",
            "TACU_M1A1SA_Base",
            "TACU_M2Bradley_Base",
            "TACU_Mi8_Base",
            "TACU_Mi8_MTV3_Base",
            "TACU_MTLB_Base",
            "TACU_MTVR_Base",
            "TACU_RHIB_Base",
            "TACU_RHIB_MK19",
            "TACU_S1203_Base",
            "TACU_T55_Base",
            "TACU_T72_Base",
            "TACU_T90_Base",
            "TACU_TIGR_233011_Base",
            "TACU_TIGR_233114_KORD_Base",
            "TACU_TIGR_233114_PK_Base",
            "TACU_UAZ_Base",
            "TACU_UAZ_DSHKM_Base",
            "TACU_UAZ_Open_Base",
            "TACU_UH1H_Base",
            "TACU_UH60_Base",
            "TACU_Ural_Base",
            "TACU_Ural_Open_Base",
            // Turrets
            "TACU_MK6_Base",
            "TACU_HMG_50",
            "TACU_HMG_50_Low",
            "TACU_Mini_Spike_AT",
            "TACU_ZU23_base",
            "TACU_AGS_base",
            "TACU_D30_base",
            "TACU_D30AT_base",
            "TACU_DSHKM_base",
            "TACU_DSHKM_Mini_base",
            "TACU_FIM92_base",
            "TACU_IGLA_base",
            "TACU_KORD_base",
            "TACU_KORD_Mini_base",
            "TACU_KORNET_AT4_base",
            "TACU_L11A1_base",
            "TACU_L11A1_MiniTripod_base",
            "TACU_L134A1_base",
            "TACU_M119_base",
            "TACU_M220_TOW_base",
            "TACU_Metis_base",
            "TACU_MK19_base",
            "TACU_RBS70_base",
            "TACU_SearchLight_base"
        };
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {
            "tacu_main",
            "CUP_Vehicles_LoadOrder",
            "RF_Data_Loadorder"
        };
        author = ECSTRING(main,Author);
        authors[] = {"Mike, GilleeDoo"};
        url = ECSTRING(main,URL);
        VERSION_CONFIG;
    };
};

#include "CfgFactionClasses.hpp"
#include "CfgVehicles.hpp"
